[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  port = 8888
  publish = "dist"
  targetPort = 8080

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "@netlify/plugin-lambda"

[functions]
  directory = "functions"
